### ISSUE TITLE
Some images are not showing in the main README

### ISSUE THREAD

**Issue by abiwinanda** [udacity/nd063-c3-design-for-security-project-starter#3]
Hi I think some screenshots in the main readme are not visible either due to broken link or the images are not present at the specified path. These are some which I found in the main readme:

![image](https://user-images.githubusercontent.com/31567498/104851857-20e04800-592a-11eb-9e09-dc1e4ac4fbf7.png)

![image](https://user-images.githubusercontent.com/31567498/104851861-25a4fc00-592a-11eb-80a5-f02c489f136c.png)

![image](https://user-images.githubusercontent.com/31567498/104851864-2c337380-592a-11eb-8973-4e2fda33c463.png)

![image](https://user-images.githubusercontent.com/31567498/104851880-3a818f80-592a-11eb-8976-9003f3057524.png)

**Comment by ronny-udacity** [comment]
Fixed the image files directory.
